name: DevSecOps CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}
  ECS_SERVICE: ${{ secrets.ECS_SERVICE }}

jobs:
  security-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

    #---Python-security scan (SAST)
      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run Bandit security scan
        run: |
          pip install bandit
          bandit -r app

    #---Dependecy vulnerablity scan 
      - name: Scan dependencies
        run: |
          pip install pip-audit
          pip-audit --strict

    #---Terraform security scan
      - name: Terraform security scan
        run: |
          pip install checkov
          checkov -d terraform/

    #---configure aws credentials
      - name: AWS configure
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
        
    #---login to ECR
      - name: login to ECR
        uses: aws-actions/amazon-ecr-login@v2

    #---Build docker image
      - name: Build Docker image
        run: |
          docker build -t fastapi-app:${{ github.run_number }} ./auth-service

    #---container security scan
      - name: Scan docker image
        uses: aquasecurity/trivy-action@0.20.0
        with: 
          image-ref: fastapi-app:${{ github.run_number }}

    #---Tag docker image
      - name: Tag image
        run: |
          IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}
    
          docker tag fastapi-app:${{ github.run_number }} $IMAGE_URI:${{ github.run_number }}
          docker tag fastapi-app:${{ github.run_number }} $IMAGE_URI:latest

    #---Push image to ECR
      - name: Push Image
        run: |
          IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}
    
          docker push $IMAGE_URI:${{ github.run_number }}
          docker push $IMAGE_URI:latest

    #---Deploy to ECS
      - name: Deploy ECS Service
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service $ECS_SERVICE \
            --force-new-deployment