name: DevSecOps CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}
  ECS_SERVICE: ${{ secrets.ECS_SERVICE }}

jobs:
  security-and-deploy:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        # ----------------------------
        # Python Security Scan (SAST)
        # ----------------------------
        - name: Install Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.11"

        - name: Run Bandit Security Scan
          run: |
            pip install bandit
            bandit -r app

        # ----------------------------
        # Dependency Vulnerability Scan
        # ----------------------------
        - name: Scan Dependencies
          run: |
            pip install pip-audit
            pip-audit

        # ----------------------------
        # Terraform Security Scan
        # ----------------------------
        - name: Terraform Security Scan
          run: |
            pip install checkov
            checkov -d terraform/

        # ----------------------------
        # Configure AWS Credentials
        # ----------------------------
        - name: Configure AWS
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

        # ----------------------------
        # Login to ECR
        # ----------------------------
        - name: Login to ECR
          uses: aws-actions/amazon-ecr-login@v2

        # ----------------------------
        # Build Docker Image
        # ----------------------------
        - name: Build Docker Image
          run: |
            docker build -t fastapi-app .

        # ----------------------------
        # Container Security Scan
        # ----------------------------
        - name: Scan Docker Image
          uses: aquasecurity/trivy-action@master
          with:
            image-ref: fastapi-app:latest

        # ----------------------------
        # Tag Docker Image
        # ----------------------------
        - name: Tag Image
          run: |
            docker tag fastapi-app:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest

        # ----------------------------
        # Push Image to ECR
        # ----------------------------
        - name: Push Image
          run: |
            docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest

        # ----------------------------
        # Deploy to ECS
        # ----------------------------
        - name: Deploy ECS Service
          run: |
            aws ecs update-service \
              --cluster $ECS_CLUSTER \
              --service $ECS_SERVICE \
              --force-new-deployment